## Predicting Fatal Accidents

In [1]:
import json
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
from config import db_password

In [3]:
file_dir = 'C://Users/sd0066/Documents/GitHub/Final/Resources'

In [4]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/accident_db"

In [5]:
engine = create_engine(db_string)

In [6]:
# fetch data from database
cursor = engine.execute('SELECT "REGIONNAME" as "region", "MONTHNAME" as "month", "LGT_CONDNAME" as "light_condition", "WEATHERNAME" as "weather", "MAK_MODNAME" as "makmod", "MOD_YEAR" as "year", "OUTCOME" as "outcome"\
FROM accident2020 LEFT JOIN vehicle2020 ON accident2020."CASENUM" = vehicle2020."CASENUM" UNION ALL \
SELECT "REGIONNAME" as "region",  "MONTHNAME" as "month", "LGT_CONDNAME" as "light_condition", "WEATHER1NAME" as "weather","MAK_MODNAME" as "makmod", "MOD_YEAR" as "year","OUTCOME" as "outcome" FROM accident2019 \
LEFT JOIN vehicle2019 ON accident2019."CASENUM" = vehicle2019."CASENUM"').fetchall()

In [7]:
accident_df = pd.DataFrame(cursor, columns=["region","month","light_condtion","weather","make_and_model","year","outcome"])
accident_df

region     month  \
0       Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...     March   
1       South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   January   
2       South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   January   
3       West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...   January   
4          Northeast (PA, NJ, NY, NH, VT, RI, MA, ME, CT)   January   
...                                                   ...       ...   
163558  West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...  December   
163559  Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...      July   
163560  Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...      July   
163561  Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...      July   
163562  Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...      July   

            light_condtion       weather make_and_model  year  outcome  
0             Not Reported  Not Reported           None  None        0  
1             Not Reported         Clear           None  None        0  
2                 Daylight         Clear           None  None        0  
3                 Daylight          Snow           None  None        0  
4       Dark - Not Lighted          Snow           None  None        0  
...                    ...           ...            ...   ...      ...  
163558      Dark - Lighted        Cloudy           None  None        0  
163559      Dark - Lighted         Clear           None  None        0  
163560            Daylight         Clear           None  None        0  
163561            Daylight         Clear           None  None        0  
163562            Daylight        Cloudy           None  None        0  

[163563 rows x 7 columns]

In [8]:
# make dummies for categorical data
dummy_df = pd.get_dummies(accident_df, columns=["region","month","light_condtion","weather","make_and_model","year"])
dummy_df.head()

outcome  region_Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, IA, MO, KS)  \
0        0                                                  1                 
1        0                                                  0                 
2        0                                                  0                 
3        0                                                  0                 
4        0                                                  0                 

   region_Northeast (PA, NJ, NY, NH, VT, RI, MA, ME, CT)  \
0                                                  0       
1                                                  0       
2                                                  0       
3                                                  0       
4                                                  1       

   region_South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA, FL, AL, MS, LA, AR, OK, TX)  \
0                                                  0                                   
1                                                  1                                   
2                                                  1                                   
3                                                  0                                   
4                                                  0                                   

   region_West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, WY, AK, HI)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  1                  
4                                                  0                  

   month_April  month_August  month_December  month_February  month_January  \
0            0             0               0               0              0   
1            0             0               0               0              1   
2            0             0               0               0              1   
3            0             0               0               0              1   
4            0             0               0               0              1   

   ...  weather_Cloudy  weather_Fog, Smog, Smoke  \
0  ...               0                         0   
1  ...               0                         0   
2  ...               0                         0   
3  ...               0                         0   
4  ...               0                         0   

   weather_Freezing Rain or Drizzle  weather_Not Reported  weather_Other  \
0                                 0                     1              0   
1                                 0                     0              0   
2                                 0                     0              0   
3                                 0                     0              0   
4                                 0                     0              0   

   weather_Rain  weather_Reported as Unknown  weather_Severe Crosswinds  \
0             0                            0                          0   
1             0                            0                          0   
2             0                            0                          0   
3             0                            0                          0   
4             0                            0                          0   

   weather_Sleet or Hail  weather_Snow  
0                      0             0  
1                      0             0  
2                      0             0  
3                      0             1  
4                      0             1  

[5 rows x 39 columns]

In [9]:
y = dummy_df ["outcome"]
X = dummy_df .drop(columns="outcome")

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(122672, 38)

In [11]:
X_test.shape

(40891, 38)

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [13]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [14]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            0       0
1            0       0
2            0       0
3            0       0
4            0       0
5            0       0
6            0       0
7            0       0
8            0       0
9            0       0
10           0       0
11           0       0
12           0       0
13           0       0
14           0       0
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [15]:
from sklearn.metrics import confusion_matrix, classification_report

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.979922232276051


In [17]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[40070     0]
 [  821     0]]


In [18]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     40070
           1       0.00      0.00      0.00       821

    accuracy                           0.98     40891
   macro avg       0.49      0.50      0.49     40891
weighted avg       0.96      0.98      0.97     40891



C:\Users\sd0066\Anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sd0066\Anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sd0066\Anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Naive Random Oversampling

In [19]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [20]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({1: 120210, 0: 120210})

In [21]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

random_over_model = LogisticRegression(solver='lbfgs', random_state=1)
random_over_model.fit(X_resampled, y_resampled)

C:\Users\sd0066\Anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [22]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = random_over_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6158990037835737

In [23]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[29738, 10332],
       [  419,   402]], dtype=int64)

In [24]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.74      0.49      0.85      0.60      0.37     40070
          1       0.04      0.49      0.74      0.07      0.60      0.35       821

avg / total       0.97      0.74      0.49      0.83      0.60      0.37     40891



### SMOTE Oversampling

In [25]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({1: 120210, 0: 120210})

In [26]:
# Train the Logistic Regression model using the resampled data
smote_model = LogisticRegression(solver='lbfgs', random_state=1)
smote_model.fit(X_resampled, y_resampled)

C:\Users\sd0066\Anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [27]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = smote_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6109110366237891

In [28]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[31925,  8145],
       [  472,   349]], dtype=int64)

In [29]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.80      0.43      0.88      0.58      0.35     40070
          1       0.04      0.43      0.80      0.07      0.58      0.33       821

avg / total       0.97      0.79      0.43      0.86      0.58      0.35     40891



# Undersampling

In [30]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.under_sampling import RandomUnderSampler
ros = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 2462, 1: 2462})

In [31]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
random_under_model = LogisticRegression(solver='lbfgs', random_state=1)
random_under_model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [32]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = random_under_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6131662860396255

In [33]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[29519, 10551],
       [  419,   402]], dtype=int64)

In [34]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.74      0.49      0.84      0.60      0.37     40070
          1       0.04      0.49      0.74      0.07      0.60      0.35       821

avg / total       0.97      0.73      0.49      0.83      0.60      0.37     40891



# Combination (Over and Under) Sampling

In [35]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({0: 55706, 1: 60692})

In [36]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
combo_model = LogisticRegression(solver='lbfgs', random_state=1)
combo_model.fit(X_resampled, y_resampled)

C:\Users\sd0066\Anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [37]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = combo_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5896766681449972

In [38]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[25001, 15069],
       [  365,   456]], dtype=int64)

In [39]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.62      0.56      0.76      0.59      0.35     40070
          1       0.03      0.56      0.62      0.06      0.59      0.34       821

avg / total       0.97      0.62      0.56      0.75      0.59      0.35     40891



### Balanced Random Forest Classifier

In [40]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
random_forest_model = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
random_forest_model.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [41]:
# Calculated the balanced accuracy score
y_pred = random_forest_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6201680706753436

In [42]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[27591, 12479],
       [  368,   453]], dtype=int64)

In [43]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.69      0.55      0.81      0.62      0.39     40070
          1       0.04      0.55      0.69      0.07      0.62      0.37       821

avg / total       0.97      0.69      0.55      0.80      0.62      0.38     40891

